name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./
      - run: crystal eval "puts 1337"
      - run: npm test
      - run: npm audit --audit-level=moderate
