name: CI (release)

on:
  push:
    branches:
      - v1
  schedule:
    - cron: '0 6 * * 6'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: oprypin/install-crystal@v1
      - run: crystal eval "puts 1337"
